Milestone 1
EleonoraGalieva/MyWallet pull request #2
Opened 2021-03-27 14:01 UTC by EleonoraGalieva

Images of main pages are made in figma (link in readme). Though this pr has some css in it, please don't pay attention to it for now.

2021-03-29 17:10 UTC, gmltA commented
I don't see any HTML tags on your figma muckups.

2021-04-05 14:32 UTC, gmltA requested changes
Can you please make your PR follow the [acceptance criteria](https://github.com/gmltA/FrontEnd_tasks#acceptance-criteria)? I need only images in it's content.

2021-04-25 15:09 UTC, gmltA reviewed
I'm messed up. What is this PR for? 2 or 3 milestone?

2021-04-25 15:48 UTC, EleonoraGalieva commented
This pr is for 3 milestone(ui design).

2021-04-26 19:45 UTC, EleonoraGalieva commented
I've deleted js files from this pr so it follows the acceptance criteria of milestone 3 (ui design).

2021-05-01 14:53 UTC, gmltA commented
Where's the deployment link?

2021-05-02 14:52 UTC, EleonoraGalieva commented
Added deployment link: https://eleonoragalieva.github.io/MyWallet

2021-05-05 18:47 UTC, gmltA reviewed
That's a <kbd>6</kbd> for now. Add `:hover` and `:focus` styles to interactive elements.

2021-05-05 18:47 UTC, gmltA commented on categories.html
> +                <p>Groceries</p>
![image](https://user-images.githubusercontent.com/138737/117192906-ec19d300-adea-11eb-8d61-0cae8986a3df.png)

2021-05-05 18:47 UTC, gmltA commented on css/styles.css
> +}
Well, you have to come up with own focus styles then.

2021-05-11 15:16 UTC, EleonoraGalieva commented
What else can I fix? I also have a theme-change, but it uses some js, which is in diffrenet branch, so it is not showing fully on this one (https://github.com/EleonoraGalieva/MyWallet/blob/Front-end-basics/js/theme-change.js).

2021-05-12 19:17 UTC, gmltA commented
Add `focus` styles to interactive elements to improve the mark. They are still missing.

2021-05-13 20:45 UTC, EleonoraGalieva commented on css/styles.css
> +
I also have some :focus on input in all forms.

2021-05-14 17:47 UTC, gmltA approved these changes
Okay, that's a <kbd>9</kbd>.

2021-05-14 17:59 UTC, EleonoraGalieva commented
Great!)

2021-05-14 18:00 UTC, merged